### ISSUE TITLE
ValueError: operands could not be broadcast together

### ISSUE THREAD

**Issue by sunmouren** [JonasBchrt/snapshot-gnss-algorithms#8]
![image](https://github.com/user-attachments/assets/3e894218-935e-4547-b24f-4470789f59b3)

**Comment by JonasBchrt** [comment]
Some questions before I can comment:

* Are you just running the example or did you modify the code yourself or are using different data?
* Which Python version are you using? (`python -V`) The code has been tested with Python 3.7 only.
* Which Python package versions are you using? (`pip` freeze`)

To me, it looks like some Python package may have introduced a breaking change.

**Comment by sunmouren** [comment]
Sorry, it's my mistake. I made a mistake in handling the utc shape.

**Comment by sunmouren** [comment]
> Some questions before I can comment:
> 
> * Are you just running the example or did you modify the code yourself or are using different data?
> * Which Python version are you using? (`python -V`) The code has been tested with Python 3.7 only.
> * Which Python package versions are you using? (`pip` freeze`)
> 
> To me, it looks like some Python package may have introduced a breaking change.

Sorry, it's my mistake. I made a mistake in handling the utc shape.
